<?php
$_GET['id'] = 72;
ob_start();
require __DIR__ . '/../api/download_pmapc_pdf.php';
$output = ob_get_clean();

echo "PDF Output Length for ID 72: " . strlen($output) . " bytes\n";
echo "Contains F01? " . (strpos($output, 'FORMATO PMAPC-F01') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F02? " . (strpos($output, 'FORMATO PMAPC-F02') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F03? " . (strpos($output, 'FORMATO PMAPC-F03') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F04? " . (strpos($output, 'FORMATO PMAPC-F04') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F05? " . (strpos($output, 'FORMATO PMAPC-F05') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F06? " . (strpos($output, 'FORMATO PMAPC-F06') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F07? " . (strpos($output, 'FORMATO PMAPC-F07') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F08? " . (strpos($output, 'FORMATO PMAPC-F08') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F09? " . (strpos($output, 'FORMATO PMAPC-F09') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F10? " . (strpos($output, 'FORMATO PMAPC-F10') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F11? " . (strpos($output, 'FORMATO PMAPC-F11') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F12? " . (strpos($output, 'FORMATO PMAPC-F12') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F12A? " . (strpos($output, 'FORMATO PMAPC-F12A') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F12B? " . (strpos($output, 'FORMATO PMAPC-F12B') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F12C? " . (strpos($output, 'FORMATO PMAPC-F12C') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F13? " . (strpos($output, 'FORMATO PMAPC-F13') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F14? " . (strpos($output, 'FORMATO PMAPC-F14') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F15? " . (strpos($output, 'FORMATO PMAPC-F15') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F15A? " . (strpos($output, 'FORMATO PMAPC-F15A') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F15B? " . (strpos($output, 'FORMATO PMAPC-F15B') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F15C? " . (strpos($output, 'FORMATO PMAPC-F15C') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F16? " . (strpos($output, 'FORMATO PMAPC-F16') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F17? " . (strpos($output, 'FORMATO PMAPC-F17') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F18? " . (strpos($output, 'FORMATO PMAPC-F18') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F19? " . (strpos($output, 'FORMATO PMAPC-F19') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F20? " . (strpos($output, 'FORMATO PMAPC-F20') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F21? " . (strpos($output, 'FORMATO PMAPC-F21') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F22? " . (strpos($output, 'FORMATO PMAPC-F22') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F22A? " . (strpos($output, 'FORMATO PMAPC-F22A') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F23? " . (strpos($output, 'FORMATO PMAPC-F23') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F24? " . (strpos($output, 'FORMATO PMAPC-F24') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F25? " . (strpos($output, 'FORMATO PMAPC-F25') !== false ? 'YES' : 'NO') . "\n";
echo "Contains F26? " . (strpos($output, 'FORMATO PMAPC-F26') !== false ? 'YES' : 'NO') . "\n";
